apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
  namespace: ping-pong-ns
spec:
  type: ClusterIP
  selector:
    app: ping-pong
  ports:
    - name: http
      protocol: TCP
      port: 2345
      targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  namespace: ping-pong-ns
spec:
  type: ClusterIP
  selector:
    app: log-output
  ports:
    - name: http
      protocol: TCP
      port: 2345
      targetPort: 3000
