apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: ping-pong-ns
type: Opaque
data:
    postgres-user: ENC[AES256_GCM,data:hEBKTgEO2tIFMCxt,iv:Z4IJ2HJIt0qB+1pWrNlVQLGB4vbyYW5xDF/9v+Y+6Jc=,tag:kaB21XJ/W87Ot9uzzHphfA==,type:str]
    postgres-password: ENC[AES256_GCM,data:jnc+GzZTYYgck15C,iv:ZBrhHD/8k3Hz6mAE2XSRsqetEAYSSWUkuX6D2QIELFQ=,tag:JVqjyGcfl8XJuWl7vwFqnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age167kr29lnhsua7arhufctcgufdugjkeyrj5jchn6hte2tetfclc0sdc7hzk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5b3hCZVlvVG4ycWZSQ2lI
            ZDBQaHRHSzZjT2JmbjlscFFZdjFwUGhlZWhvClJpMmgwWkVqT2NMZTZXUmcwYW1l
            ZDEzNlVRU3lKQWRBWTczYkp0aERIVnMKLS0tIHZoSjVOQytYUjRIZXhJMXBlUDl4
            b3lPdXB4UHprdGhnZmsyOTNyeVpuY3MKJV9ZL3TvSPpBI3+PJlf7oxZznTYz7aOS
            Gxv39xiTR4Uamry9fa6pjQWvlsi51vsRUWrV2e8MEXkuzemj8QCWFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-10T10:28:27Z"
    mac: ENC[AES256_GCM,data:W3sgUx5P0XIg1TU0PtsiP3AvWGf6b5BoLL+7c/F56q5cKUBXcvLbW8VCC+3wLnFKiKEaRZLdHDUKyZkLP67wV8MwGlDYWzaUpvoHuOEsE19slYlQ4uC5MPPAtmgj8ETHt7wY/1CiGJi+efNGV2ZmVzORoQ5S5EbX9ZNbiWqiwIE=,iv:qSTWZBUGEKz9InBh0bixhBqsCy3aDfocOdlcnpFyUBo=,tag:PKWIai4iCr6sVUsY5UncSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.8.0-rc.1
