apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-random-wiki
  namespace: todo-ns
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-random-wiki
            image: tryfonm/todo-random-wiki:v2.10
          restartPolicy: Never
