apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-svc
  namespace: todo-ns
spec:
  type: ClusterIP
  selector:
    app: todo-frontend
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-svc
  namespace: todo-ns
spec:
  type: ClusterIP
  selector:
    app: todo-backend
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: todo-random-wiki-svc
  namespace: todo-ns
spec:
  type: ClusterIP
  selector:
    app: todo-random-wiki
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3003
