apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: todo-ns
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432     # Port on the service
      targetPort: 5432  # Port on the pods
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-ss
  namespace: todo-ns
spec:
  serviceName: postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-claim  # Reference the existing PVC name
      containers:
        - name: postgres
          image: tryfonm/postgres:v2.10
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          env:
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password