apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: todo-ns
type: Opaque
data:
    postgres-user: ENC[AES256_GCM,data:ccmqoWfK9snsXI5P,iv:pRI73szjfSXfN9abE7ctrOaz1sS9s0pVGWJDOiMfFlI=,tag:rH5834yq5NF8xaEKYk70Cg==,type:str]
    postgres-password: ENC[AES256_GCM,data:4hU9n/u5omtwdnJ0,iv:ZAHalwe3nKibOlh2AgsNNiZ7jlLHk8Bcb8LhnmBIV2o=,tag:Pl9wF7NdjLNuRyzODbhtYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age167kr29lnhsua7arhufctcgufdugjkeyrj5jchn6hte2tetfclc0sdc7hzk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeEdkY3lsbXdFaktwbEhr
            VW8vZlNvYUdPdE41aUlLRUpjRkJxT1NjTkRVCm1teGRHRWgrOVh2OUNGb2JBTjF1
            WHdpTXlvYkVJWktXUlN2SGhXV3BEbTgKLS0tIGtpblRlWUNPbjR1RThHMy9aRG1O
            WXY0MmdZTTdTUkpqRmM0TUVRWFZiUUEKCYfIRNeGPQtngfsHThxupk2lgIQz5ffe
            UWmUboAFqK3Dj65oRgMBLeMlDLyGiSzMEHmv61OyPypAmnbTOttB0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-10T20:03:54Z"
    mac: ENC[AES256_GCM,data:NomDYu36ZsIXz0G/w/jpWERpBKvBxCFiAzYE+hGtu4om81uRHFoRUwcRuuDgtioAySrY9mh2Vk2GpnaEjX9lObOS0lLRlvQ83+oxGaG7VpifnOq3Hb/yYMItyX5XMvAK2INiKMN9PqIv6vgomnHxPPOdvdPihsYMNDLQsk2Agg4=,iv:dJ1WvEHweEuN8jPmhXT10vtQmVpM94zM0KxxmvgGe68=,tag:JsajL0zF0AibLl6iGVSTNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.8.0-rc.1
